name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.8-nodejs14

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install . --upgrade

      - name: Test
        run: pytest --cov=b_continuous_subprocess b_continuous_subprocess_test --cov-fail-under=80

      - uses: actions/upload-artifact@v2
        with:
          name: venv
          path: venv

  build-and-push:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.8-nodejs14

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Install
        run: |
          pip install wheel
          pip install twine

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
