name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.8-nodejs14

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          echo Using python: $( python --version )
          python -m venv venv
          source venv/bin/activate
          pip install . --upgrade
