name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest
    container: biomapas/cicd-full:5.0.0

    steps:
      - uses: actions/checkout@v2

      - name: Codelint
        run: |
          pip install black
          black . -S --check || exit 1

          pip install pylint
          pylint b_continuous_subprocess --fail-under 8 || exit 1

      - name: Install
        run: |
          pip install . --upgrade
          pip install -r b_continuous_subprocess_test/requirements.txt
          pip list

      - name: Test
        run: pytest --cov=b_continuous_subprocess b_continuous_subprocess_test --cov-fail-under=80

      - name: Install
        run: pip install wheel twine setuptools --upgrade

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
