name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.8-nodejs14

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          python -m pip install . --upgrade
          python -m pip list

      - name: Test
        run: python -m pytest --cov=b_continuous_subprocess b_continuous_subprocess_test --cov-fail-under=80

      - name: Install
        run: python -m pip install wheel twine

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Upload
        run: python -m twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
