name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - master

jobs:
  install-test:
    runs-on: ubuntu-latest
    container: biomapas/cicd-full:0.0.2

    steps:
      - uses: actions/checkout@v2

      - name: Codelint
        run: |
          pip install black
          black . -S --check || exit 1

          pip install pylint
          pylint b_continuous_subprocess --fail-under 8 || exit 1

      - name: Install
        run: |
          pip install . --upgrade
          pip list

      - name: Test
        run: pytest --cov=b_continuous_subprocess b_continuous_subprocess_test --cov-fail-under=80
